name: Vanguard Party
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60129
title: Vanguard Party
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0025e5'
    - '#1e0218'
    - '#fefefe'
    - '#6d72be'
    - '#fe7e71'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
