name: Vanguard Party
favicon: null
layout_spectrum: 0.25278
typography_spectrum: 0.47068
title: Vanguard Party
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#30251a'
    - '#6b5244'
    - '#dab296'
    - '#ba8a78'
    - '#a15f8b'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
