name: Vanguard Party
favicon: null
layout_spectrum: 0.25278
typography_spectrum: 0.47068
title: Vanguard Party
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000312'
    - '#adacb1'
    - '#c75974'
    - '#b4111c'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
