name: Vanguard Party
favicon: null
layout_spectrum: 0.13306917739100754
typography_spectrum: 0.017144331010058522
title: Vanguard Party
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.991839875234291
  lightness: 0.8176712980493903
  saturation: 0.6370547919068485
  rhythmicContrast: 0.3165736715309322
purpose: []
